// <auto-generated />
using System;
using EasyMicroservices.WhiteLabelsMicroservice.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyMicroservices.WhiteLabelsMicroservice.Migrations
{
    [DbContext(typeof(WhiteLabelContext))]
    [Migration("20231204093626_AddKey_WhiteLabelEntity")]
    partial class AddKey_WhiteLabelEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.ContextTableEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ContextName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ContextName");

                    b.HasIndex("TableName");

                    b.HasIndex("ContextName", "TableName")
                        .IsUnique()
                        .HasFilter("[ContextName] IS NOT NULL AND [TableName] IS NOT NULL");

                    b.ToTable("ContextTables");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContextName = "TemplateGeneratorContext",
                            TableName = "Forms"
                        },
                        new
                        {
                            Id = 2L,
                            ContextName = "TemplateGeneratorContext",
                            TableName = "FormDetails"
                        },
                        new
                        {
                            Id = 3L,
                            ContextName = "TemplateGeneratorContext",
                            TableName = "FormFills"
                        },
                        new
                        {
                            Id = 4L,
                            ContextName = "TemplateGeneratorContext",
                            TableName = "FormItems"
                        },
                        new
                        {
                            Id = 5L,
                            ContextName = "TemplateGeneratorContext",
                            TableName = "FormItemValues"
                        },
                        new
                        {
                            Id = 6L,
                            ContextName = "TemplateGeneratorContext",
                            TableName = "ItemTypes"
                        });
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.MicroserviceContextTableEntity", b =>
                {
                    b.Property<long>("MicroserviceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContextTableId")
                        .HasColumnType("bigint");

                    b.HasKey("MicroserviceId", "ContextTableId");

                    b.HasIndex("ContextTableId");

                    b.ToTable("MicroserviceContextTables");

                    b.HasData(
                        new
                        {
                            MicroserviceId = 1L,
                            ContextTableId = 1L
                        },
                        new
                        {
                            MicroserviceId = 1L,
                            ContextTableId = 2L
                        },
                        new
                        {
                            MicroserviceId = 1L,
                            ContextTableId = 3L
                        },
                        new
                        {
                            MicroserviceId = 1L,
                            ContextTableId = 4L
                        },
                        new
                        {
                            MicroserviceId = 1L,
                            ContextTableId = 5L
                        },
                        new
                        {
                            MicroserviceId = 1L,
                            ContextTableId = 6L
                        });
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.MicroserviceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceIndex")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServerDestinationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Name", "InstanceIndex")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Microservices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            InstanceIndex = 1,
                            Name = "TemplateGenerator"
                        },
                        new
                        {
                            Id = 2L,
                            InstanceIndex = 1,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 3L,
                            InstanceIndex = 1,
                            Name = "Storage"
                        });
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.WhiteLabelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("WhiteLabels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Key = new Guid("bc53b7f6-8f59-41af-b3d8-45dd1c4f57e7"),
                            Name = "ProjectName"
                        },
                        new
                        {
                            Id = 2L,
                            Key = new Guid("89d6f81c-091c-4124-8447-6ec7ecaf11bb"),
                            Name = "TenantName",
                            ParentId = 1L
                        });
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.MicroserviceContextTableEntity", b =>
                {
                    b.HasOne("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.ContextTableEntity", "ContextTable")
                        .WithMany("MicroserviceContextTables")
                        .HasForeignKey("ContextTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.MicroserviceEntity", "Microservice")
                        .WithMany("MicroserviceContextTables")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContextTable");

                    b.Navigation("Microservice");
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.WhiteLabelEntity", b =>
                {
                    b.HasOne("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.WhiteLabelEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.ContextTableEntity", b =>
                {
                    b.Navigation("MicroserviceContextTables");
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.MicroserviceEntity", b =>
                {
                    b.Navigation("MicroserviceContextTables");
                });

            modelBuilder.Entity("EasyMicroservices.WhiteLabelsMicroservice.Database.Entities.WhiteLabelEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
